nome = str(input('Digite seu nome completo: ')).strip()
print('Muito prazer em te conhecer!')
a = nome.split()
print('Seu primeiro nome é {}'.format(a[0]))
print('Seu último nome é {}'.format(a[len(a)-1]))
